name: API Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  api-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Newman
        run: npm install -g newman

      - name: Run Postman API Tests
        env:
          NRICHAUTH: ${{ secrets.NRICHAUTH }}
        run: |
          # newman run reqres.postman_collection.json --env-var "auth=$PAGEVALUE"
          newman run nrich.postman_collection.json \
            -e dev_nrich.postman_environment.json \
            -g QB_APIs.postman_globals.json \
            --env-var "auth=$NRICHAUTH"